export const synonyms = {
    "approximately": "about",
    "utilize": "use",
    "facilitate": "help",
    "construct": "build",
    "observe": "see",
    "demonstrate": "show",
    "objective": "goal",
    "initiate": "start",
    "subsequently": "later",
    "nevertheless": "however",
    "additional": "extra",
    "sufficient": "enough",
    "necessary": "needed",
    "important": "key",
    "significant": "major",
    "frequently": "often",
    "immediately": "right away",
    "specifically": "exactly",
    "generally": "usually",
    "particularly": "especially",
    "acquire": "get",
    "accomplish": "do",
    "acknowledge": "admit",
    "adequate": "enough",
    "adjacent": "next to",
    "aggregate": "total",
    "allocate": "give",
    "alternative": "choice",
    "analyze": "study",
    "anticipate": "expect",
    "apparent": "clear",
    "appreciate": "value",
    "approach": "way",
    "appropriate": "right",
    "arbitrary": "random",
    "ascertain": "find out",
    "aspect": "part",
    "assemble": "put together",
    "assess": "judge",
    "assist": "help",
    "assume": "suppose",
    "attain": "reach",
    "attribute": "trait",
    "augment": "increase",
    "authentic": "real",
    "authorize": "allow",
    "automatic": "automatic",
    "available": "ready",
    "beneficial": "helpful",
    "capable": "able",
    "category": "group",
    "cease": "stop",
    "challenge": "test",
    "circumstance": "situation",
    "clarify": "explain",
    "coherent": "clear",
    "coincide": "match",
    "collaborate": "work together",
    "commence": "start",
    "comment": "say",
    "communicate": "talk",
    "compare": "compare",
    "compensate": "pay",
    "compile": "gather",
    "complement": "match",
    "complete": "finish",
    "complex": "hard",
    "component": "part",
    "comprehend": "understand",
    "comprise": "include",
    "compute": "calculate",
    "conceive": "think",
    "concentrate": "focus",
    "concept": "idea",
    "conclude": "end",
    "concurrent": "at the same time",
    "conduct": "do",
    "confer": "give",
    "confine": "limit",
    "confirm": "prove",
    "conflict": "fight",
    "conform": "follow",
    "confront": "face",
    "confuse": "mix up",
    "conserve": "save",
    "consider": "think",
    "consist": "made of",
    "constant": "steady",
    "constitute": "make up",
    "constrain": "limit",
    "consult": "ask",
    "consume": "use",
    "contact": "touch",
    "contain": "hold",
    "contemporary": "modern",
    "contend": "argue",
    "context": "setting",
    "continue": "keep going",
    "contract": "shrink",
    "contradict": "go against",
    "contrary": "opposite",
    "contrast": "difference",
    "contribute": "give",
    "controversy": "dispute",
    "convene": "meet",
    "converse": "talk",
    "convert": "change",
    "convey": "carry",
    "convince": "persuade",
    "cooperate": "work together",
    "coordinate": "organize",
    "core": "center",
    "corporate": "company",
    "correspond": "match",
    "couple": "two",
    "create": "make",
    "credit": "trust",
    "criteria": "standards",
    "crucial": "key",
    "culture": "way of life",
    "currency": "money",
    "cycle": "circle",
    "data": "facts",
    "debate": "argue",
    "decade": "ten years",
    "decide": "choose",
    "decline": "go down",
    "decrease": "lessen",
    "deduce": "figure out",
    "define": "explain",
    "definite": "sure",
    "denote": "mean",
    "deny": "say no",
    "depart": "leave",
    "depend": "rely",
    "depict": "show",
    "derive": "get",
    "design": "plan",
    "despite": "even though",
    "detect": "find",
    "determine": "decide",
    "develop": "grow",
    "deviate": "stray",
    "device": "tool",
    "devote": "give",
    "differentiate": "tell apart",
    "dimension": "size",
    "diminish": "lessen",
    "direct": "straight",
    "discrete": "separate",
    "discriminate": "tell apart",
    "display": "show",
    "dispose": "get rid of",
    "distinct": "different",
    "distinguish": "tell apart",
    "distribute": "give out",
    "diverse": "varied",
    "document": "paper",
    "domain": "area",
    "domestic": "home",
    "dominate": "control",
    "draft": "rough copy",
    "drama": "play",
    "duration": "length",
    "dynamic": "changing",
    "economy": "money system",
    "edit": "change",
    "element": "part",
    "eliminate": "remove",
    "emerge": "appear",
    "emphasis": "stress",
    "employ": "use",
    "enable": "allow",
    "encounter": "meet",
    "encourage": "urge",
    "energy": "power",
    "enforce": "make happen",
    "enhance": "improve",
    "enormous": "huge",
    "ensure": "make sure",
    "entity": "thing",
    "environment": "surroundings",
    "equate": "equal",
    "equipment": "tools",
    "equivalent": "equal",
    "erode": "wear away",
    "error": "mistake",
    "establish": "set up",
    "estimate": "guess",
    "ethic": "moral",
    "ethnic": "racial",
    "evaluate": "judge",
    "eventual": "final",
    "evident": "clear",
    "evolve": "develop",
    "exceed": "go over",
    "exclude": "leave out",
    "exhibit": "show",
    "expand": "grow",
    "expert": "specialist",
    "explicit": "clear",
    "exploit": "use",
    "export": "send out",
    "expose": "show",
    "external": "outside",
    "extract": "pull out",
    "factor": "part",
    "feature": "trait",
    "federal": "national",
    "fee": "charge",
    "file": "document",
    "final": "last",
    "finance": "money",
    "finite": "limited",
    "flexible": "bendable",
    "fluctuate": "change",
    "focus": "center",
    "format": "layout",
    "formula": "rule",
    "forthcoming": "coming",
    "fortune": "luck",
    "forum": "meeting",
    "foundation": "base",
    "framework": "structure",
    "frequent": "often",
    "function": "work",
    "fundamental": "basic",
    "furthermore": "also",
    "gender": "sex",
    "generate": "create",
    "generation": "age group",
    "globe": "world",
    "goal": "aim",
    "grade": "level",
    "grant": "give",
    "guarantee": "promise",
    "guideline": "rule",
    "hence": "so",
    "hierarchy": "order",
    "highlight": "emphasize",
    "hypothesis": "guess",
    "identical": "same",
    "identify": "name",
    "ideology": "belief",
    "ignorance": "not knowing",
    "illustrate": "show",
    "image": "picture",
    "immigrate": "move in",
    "impact": "effect",
    "implement": "carry out",
    "implicate": "involve",
    "implicit": "implied",
    "imply": "suggest",
    "impose": "force",
    "incentive": "reward",
    "incidence": "occurrence",
    "incline": "lean",
    "income": "earnings",
    "incorporate": "include",
    "index": "list",
    "indicate": "show",
    "individual": "person",
    "induce": "cause",
    "inevitable": "unavoidable",
    "infer": "conclude",
    "infrastructure": "foundation",
    "inherent": "built-in",
    "inhibit": "prevent",
    "initial": "first",
    "injure": "hurt",
    "innovate": "create",
    "input": "put in",
    "insert": "put in",
    "insight": "understanding",
    "inspect": "examine",
    "instance": "example",
    "institute": "organization",
    "instruct": "teach",
    "integral": "essential",
    "integrate": "combine",
    "integrity": "honesty",
    "intelligence": "smarts",
    "intense": "strong",
    "interact": "work together",
    "intermediate": "middle",
    "internal": "inside",
    "interpret": "explain",
    "interval": "gap",
    "intervene": "step in",
    "intrinsic": "inherent",
    "investigate": "look into",
    "invoke": "call on",
    "involve": "include",
    "isolate": "separate",
    "issue": "problem",
    "item": "thing",
    "job": "work",
    "journal": "diary",
    "justify": "explain",
    "label": "tag",
    "labor": "work",
    "lack": "need",
    "layer": "level",
    "lecture": "talk",
    "legal": "lawful",
    "legislate": "make laws",
    "levy": "charge",
    "liberal": "free",
    "license": "permit",
    "likewise": "also",
    "link": "connect",
    "locate": "find",
    "logic": "reason",
    "maintain": "keep",
    "major": "big",
    "manipulate": "control",
    "manual": "handbook",
    "margin": "edge",
    "mature": "grown",
    "maximize": "increase",
    "mechanism": "system",
    "media": "news",
    "mediate": "help",
    "medical": "health",
    "medium": "middle",
    "mental": "mind",
    "method": "way",
    "migrate": "move",
    "military": "army",
    "minimal": "least",
    "minimize": "reduce",
    "minimum": "least",
    "ministry": "department",
    "minor": "small",
    "minus": "less",
    "mode": "way",
    "modify": "change",
    "monitor": "watch",
    "motive": "reason",
    "mutual": "shared",
    "narrative": "story",
    "narrow": "thin",
    "nation": "country",
    "native": "local",
    "nature": "world",
    "negative": "bad",
    "neglect": "ignore",
    "negotiate": "bargain",
    "network": "web",
    "neutral": "impartial",
    "nonetheless": "however",
    "norm": "standard",
    "normal": "usual",
    "notion": "idea",
    "notwithstanding": "despite",
    "nuclear": "atomic",
    "obtain": "get",
    "obvious": "clear",
    "occupy": "fill",
    "occur": "happen",
    "odd": "strange",
    "offset": "balance",
    "ongoing": "continuing",
    "option": "choice",
    "orient": "direct",
    "outcome": "result",
    "output": "product",
    "overall": "general",
    "overlap": "cover",
    "overseas": "abroad",
    "panel": "board",
    "paradigm": "model",
    "paragraph": "section",
    "parallel": "side by side",
    "parameter": "limit",
    "participate": "take part",
    "partner": "teammate",
    "passive": "inactive",
    "perceive": "see",
    "percent": "part",
    "period": "time",
    "persist": "continue",
    "perspective": "view",
    "phase": "stage",
    "phenomenon": "event",
    "philosophy": "belief",
    "physical": "bodily",
    "plus": "more",
    "policy": "rule",
    "portion": "part",
    "pose": "present",
    "positive": "good",
    "possess": "have",
    "potential": "possible",
    "poverty": "poor",
    "practitioner": "worker",
    "precede": "come before",
    "precise": "exact",
    "predict": "forecast",
    "predominant": "main",
    "preliminary": "first",
    "premise": "assumption",
    "prescription": "order",
    "presence": "being there",
    "preserve": "keep",
    "press": "push",
    "presume": "assume",
    "previous": "earlier",
    "primary": "main",
    "prime": "best",
    "principal": "main",
    "principle": "rule",
    "prior": "earlier",
    "priority": "importance",
    "proceed": "continue",
    "process": "method",
    "professional": "expert",
    "prohibit": "forbid",
    "project": "plan",
    "promote": "advance",
    "proportion": "part",
    "prospect": "possibility",
    "protocol": "rule",
    "psychology": "mind study",
    "publication": "book",
    "publish": "print",
    "purchase": "buy",
    "purpose": "reason",
    "pursue": "follow",
    "qualify": "meet",
    "quality": "trait",
    "quarter": "fourth",
    "radical": "extreme",
    "random": "chance",
    "range": "span",
    "rank": "level",
    "rapid": "fast",
    "ratio": "proportion",
    "rational": "reasonable",
    "react": "respond",
    "recover": "get back",
    "refine": "improve",
    "reflect": "think",
    "reform": "change",
    "regime": "government",
    "region": "area",
    "register": "record",
    "regulate": "control",
    "reinforce": "strengthen",
    "reject": "refuse",
    "relate": "connect",
    "relax": "rest",
    "release": "let go",
    "relevant": "related",
    "reluctant": "unwilling",
    "rely": "depend",
    "remain": "stay",
    "remove": "take away",
    "require": "need",
    "research": "study",
    "resolve": "solve",
    "resource": "supply",
    "respond": "answer",
    "restore": "bring back",
    "restrain": "hold back",
    "restrict": "limit",
    "retain": "keep",
    "reveal": "show",
    "revenue": "income",
    "reverse": "opposite",
    "revise": "change",
    "revolution": "change",
    "rigid": "stiff",
    "role": "part",
    "route": "path",
    "scenario": "situation",
    "schedule": "plan",
    "scheme": "plan",
    "scope": "range",
    "section": "part",
    "sector": "area",
    "secure": "safe",
    "seek": "look for",
    "select": "choose",
    "sequence": "order",
    "series": "set",
    "severe": "serious",
    "sex": "gender",
    "shift": "change",
    "similar": "alike",
    "simulate": "imitate",
    "simultaneous": "at the same time",
    "slight": "small",
    "smooth": "even",
    "sole": "only",
    "somewhat": "a bit",
    "source": "origin",
    "specific": "exact",
    "specify": "state",
    "sphere": "area",
    "stable": "steady",
    "statistic": "number",
    "status": "state",
    "straightforward": "simple",
    "strategy": "plan",
    "stress": "pressure",
    "strict": "severe",
    "structure": "form",
    "style": "way",
    "submit": "send",
    "subsequent": "following",
    "subsidy": "aid",
    "substitute": "replace",
    "successor": "follower",
    "sum": "total",
    "summary": "overview",
    "supplement": "add",
    "supply": "provide",
    "survey": "study",
    "survive": "live",
    "suspend": "stop",
    "sustain": "maintain",
    "symbol": "sign",
    "symptom": "sign",
    "synthesis": "combination",
    "system": "method",
    "target": "goal",
    "task": "job",
    "team": "group",
    "technical": "mechanical",
    "technique": "method",
    "technology": "tools",
    "temporary": "short-term",
    "tense": "tight",
    "terminate": "end",
    "text": "words",
    "theme": "topic",
    "theory": "idea",
    "thereby": "by that",
    "therefore": "so",
    "thesis": "argument",
    "thorough": "complete",
    "though": "although",
    "threat": "danger",
    "threshold": "limit",
    "thus": "so",
    "topic": "subject",
    "trace": "track",
    "tradition": "custom",
    "transfer": "move",
    "transform": "change",
    "transit": "travel",
    "transmit": "send",
    "transport": "carry",
    "trend": "pattern",
    "trigger": "cause",
    "ultimate": "final",
    "undergo": "experience",
    "underlie": "support",
    "undertake": "do",
    "uniform": "same",
    "unify": "unite",
    "unique": "one of a kind",
    "universe": "world",
    "unlike": "different",
    "unprecedented": "never before",
    "update": "refresh",
    "upgrade": "improve",
    "uphold": "support",
    "upset": "disturb",
    "urban": "city",
    "urge": "push",
    "usage": "use",
    "utter": "say",
    "valid": "true",
    "vary": "differ",
    "vehicle": "car",
    "version": "form",
    "versus": "against",
    "via": "through",
    "violate": "break",
    "virtual": "almost",
    "visible": "seen",
    "vision": "sight",
    "visual": "seen",
    "vital": "essential",
    "volume": "amount",
    "voluntary": "optional",
    "welfare": "well-being",
    "whereas": "while",
    "whereby": "by which",
    "widespread": "common",
    "withdraw": "take back",
    "witness": "see"
};

/**
 * Checks if a word has a simpler synonym.
 * @param {string} word 
 * @returns {string|null} The synonym if found, else null.
 */
export const getSynonym = (word) => {
    // Strip punctuation for lookup
    const cleanWord = word.toLowerCase().replace(/[^\w]/g, '');
    return synonyms[cleanWord] || null;
}
